---
title: "Data Cleaning / Prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## General Notes

* Switched to the combined wave 14 data because of corrected ns codes
    + profile_socialgrade_cie renamed to profile_socgrade
    + profile_socialgrade_cie with no wave not found, starts with Wave 7
    + cut off at Wave 12
    
* Only kept rows where there were responses to lr questions in wave groups 1-5, 
6, 7-9, 10-12. I can change that or make it "more complicated".
  
* Variables without wave indicators
    + Age (it is as of January 2014 - approximately W1)
    + ageGroup
    + not using age_pdlW8, appears to be the same as ageW8
    + gender
    + marital -- I think it's wave 10
    + housing -- I think it's wave 10
    + profile_gross_personal
    
* Variables that seem helpful but with limited waves
    + anyUni only started in W7
    + allSourceIncome only in W6, W11
    + profile_work_stat only in W7, W11, W12, W13
    + profile_house_tenure has one with no wave, then W10 - W13
    + profile_socialgrade_cie has one with no wave, then W7, W8, W12, W13
  
* In general, profile_ variables start around W7 and after, sometimes one has no wave listed
  
* Variables I can't find:
    + `redistTST1_1`
  
* Figure out what to do about housing

## Outcome

### Category of Left-Right Wing Views

* Survey variables: 
    + lr1
    + lr2
    + lr3
    + lr4
    + lr5
* Missing data method: complete cases
* Processing: reconstruct original factor analysis (incomplete)

## Predictors

### Objective Economic Hardship

* Survey variables:
    + `profile_gross_household`
    + `working_status`
    + `profile_work_stat`
* Missing data:
* Prep process:
    + Lag income
    + Lag job status
    + Compute differences

### Subjective Economic Hardship

* Survey variables: 
    + `goodTimePurchase`, 
    + `econPersonalProsp`, 
    + `riskproverty`, 
    + `riskunemployment`, 
    + `econPersonalRetro1`
    
    -- take additive route perhaps
    -- we can decide once running models
* Missing data: 
* Processing:
    + Factor analysis
  
### Age

* Survey variables:
* Missing data:
* Processing:

### Gender

* Survey variables: `gender`
* Missing data: apply `gender` to all waves
* Processing: N/A

### Social Class

* Survey variables:
    + `profile_work_type`
    + `profile_socgrade`
* Others that may be helpful:
  + `subjClass`
  + `forcedsubjClass`

### Housing

* Survey variables:
    + `profile_house_tenure`
* Others that may be helpful:
    + `housing`
* Missing data:
* Processing:

### Education

* Survey variables:
    + `education`:

### Logged Income

* Survey variables:
    + `profile_gross_household`
    + `bes4a` (maybe can be used in the future)
    
### Future: Employment

* `work_type`: Type of occupation (e.g. manager, etc.)
    + Survey variables:
        - `ns_sec`
        - `ns_sec_analytic`
    + Missing data:
    + Processing:
